language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  #- php vendor/bin/phpcs -n --standard=psr2 cli/ src/ includes/ *.php
  #- php vendor/bin/phpunit --coverage-text
  - find  . -name '*.php' ! -path './vendor/*' -print0 | xargs -0 -n 1 php -l

install:
  - composer install

