---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install
  
script:
  - php vendor/bin/phpcs -n --standard=psr2 cli/ src/ includes/ *.php
  - php vendor/bin/phpunit --configuration test/phpunit.xml --coverage-text
...

